apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: flisol-demo
    app.openshift.io/runtime: quarkus
  name: flisol-demo
spec:
  lookupPolicy:
    local: false